#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright © 2025 Florian Marrero Liestmann <f.m.liestmann@fx-ttr.de>

load_path="$(dirname "$(realpath "$0")")/modules"

export GUILE_LOAD_PATH="${load_path}${GUILE_LOAD_PATH:+:}${GUILE_LOAD_PATH}"
export GUIX_PACKAGE_PATH="${load_path}${GUIX_PACKAGE_PATH:+:}${GUIX_PACKAGE_PATH}"

exec "$@"
